"""empty message

Revision ID: 91312145db86
Revises: 9d768503c32f
Create Date: 2020-04-10 16:08:00.177118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91312145db86'
down_revision = '9d768503c32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
