"""empty message

Revision ID: 9d768503c32f
Revises: 3476ee048143
Create Date: 2020-04-09 20:12:25.477530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d768503c32f'
down_revision = '3476ee048143'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ccv', sa.String(length=128), nullable=True))
    op.drop_constraint('user_CCV_key', 'user', type_='unique')
    op.create_unique_constraint(None, 'user', ['ccv'])
    op.drop_column('user', 'CCV')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('CCV', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='unique')
    op.create_unique_constraint('user_CCV_key', 'user', ['CCV'])
    op.drop_column('user', 'ccv')
    # ### end Alembic commands ###
